# Generated by Django 3.1.3 on 2021-02-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.TextField()),
                ('second_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.secondtable')),
            ],
        ),
    ]
